export const skillsetRating: { [key: string]: number } = {
  // 3 - expert
  // 2 - intermediate
  // 1 - beginner
  // 0 - planning to learn

  typescript: 3,
  "react.js": 3,
  html: 3,
  css: 3,
  scss: 3,
  firebase: 3,
  // sql: 3,
  git: 3,
  "c#": 1,
  // "windows forms": 1,
  "transact-sql": 1,
  java: 2,
  // flask: 1,
  django: 1,
  "bootstrap css": 2,
  // swing: 0,
  // cli: 0,
  // "file handling": 0,
  php: 2,
  mysql: 3,
  python: 2,
  postgresql: 1,
  javascript: 3,
  "restful api": 3,
  // angular: 0,
  // vue: 0,
  // svelte: 0,
  "tailwind css": 3,
   mariadb: 3,
  // pythonanywhere: 1,
  "react native": 3,
  expo: 3,
  "next.js": 3,
  // cloudinary: 1,
  // vite: 3,
  supabase: 3,
  // email.js: 0,
  // webgazer.js: 0,
  // deepseek: 0,
  nosql: 1,
  // xampp: 0,
  // "microsoft sql server": 0,
  // vercel: 0,
  gsap: 2,
  "framer motion": 1,
  // pocketbase: 0,
  jira: 2,
  figma: 3,
  webflow: 3,
  // stripe: 1,
  "amazon web services": 3,
  yii2: 1,
};
